name: springwolf-kafka

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/springwolf-kafka.yml'
      - 'springwolf-core/**'
      - 'springwolf-plugins/springwolf-kafka-plugin/**'
      - 'springwolf-examples/springwolf-kafka-example/**'
  pull_request:
    types: [ opened, synchronize, ready_for_review ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup spectral
        run: |
          echo 'extends: ["spectral:asyncapi"]' > .spectral.yaml
      - name: Lint asyncapi.json with spectral
        uses: stoplightio/spectral-action@v0.8.8
        with:
          file_glob: 'springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.json'

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run unit tests
        run: ./gradlew -p springwolf-plugins/springwolf-kafka-plugin test

      - name: Run integration tests
        run: ./gradlew -p springwolf-examples/springwolf-kafka-example test
